# Generated by Django 3.2.10 on 2023-06-12 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20230607_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogdb',
            old_name='Category_Name',
            new_name='Category',
        ),
    ]
