# Generated by Django 3.2.10 on 2023-06-13 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_category_name_blogdb_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogdb',
            old_name='Category',
            new_name='Category_Name',
        ),
    ]
