# Generated by Django 3.2.10 on 2023-06-13 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_category_blogdb_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogdb',
            old_name='Category_Name',
            new_name='Category',
        ),
    ]
