# Generated by Django 3.2.10 on 2023-06-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20230615_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydb',
            name='Category',
            field=models.CharField(max_length=100),
        ),
    ]
