# Generated by Django 3.2.10 on 2023-06-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20230615_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdb',
            name='Content',
            field=models.TextField(blank=True, max_length=10000000, null=True),
        ),
    ]
