# Generated by Django 3.2.10 on 2023-06-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_blogdb_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdb',
            name='Content',
            field=models.CharField(blank=True, max_length=10000000, null=True),
        ),
    ]
