# Generated by Django 3.2.10 on 2023-06-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_userregdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercategorydb',
            name='Category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userregdb',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userregdb',
            name='Password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userregdb',
            name='Username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
