# Generated by Django 3.2.10 on 2023-06-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20230615_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('Mail', models.CharField(max_length=100)),
            ],
        ),
    ]
