# Generated by Django 3.2.10 on 2023-06-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20230619_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=100)),
                ('Eaddress', models.CharField(max_length=100)),
            ],
        ),
    ]
