# Generated by Django 3.2.10 on 2023-06-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_commentdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogsdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100)),
                ('Blog_Title', models.CharField(max_length=500)),
                ('Date', models.DateField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Blog_Image', models.ImageField(upload_to='Blogs')),
                ('City', models.CharField(max_length=100)),
                ('Content', models.CharField(max_length=10000000)),
            ],
        ),
        migrations.RemoveField(
            model_name='commentdb',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='commentdb',
            name='Name',
        ),
    ]
